from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid
from pydantic import BaseModel, Field
from app.event_bus.events import EventType


class AlertStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"


class TrainUpdateEvent(BaseModel):
    """
    Contract 1: TRAIN_UPDATE telemetry event
    """
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    event_type: EventType = Field(default=EventType.TRAIN_UPDATE)
    train_id: str
    latitude: float
    longitude: float
    speed: float
    section: str
    delay: float
    eta: str
    priority: str = "NORMAL"
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class PredictionEvent(BaseModel):
    """
    Contract 2: PREDICTION event generated by ML inference
    """
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    event_type: EventType = Field(default=EventType.PREDICTION)
    train_id: str
    predicted_delay: float
    predicted_eta: str
    conflict_probability: float
    potential_conflict: bool
    recommendation: str
    section: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class VisionEvent(BaseModel):
    """
    Contract 3: VISION event generated by object/defect detection
    """
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    event_type: EventType = Field(default=EventType.VISION_DETECTION)
    object_type: str
    confidence: float
    location: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    bounding_box: Optional[List[float]] = None
    video_source: Optional[str] = None


class RiskAlert(BaseModel):
    """
    Contract 4: RISK ALERT generated by Risk Engine
    """
    alert_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    risk_score: float
    alert_level: str
    location: str
    related_train_ids: List[str] = Field(default_factory=list)
    related_events: List[str] = Field(default_factory=list)
    recommendation: str
    status: AlertStatus = AlertStatus.ACTIVE
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    escalated: bool = False
