from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid
from pydantic import BaseModel, Field
from app.event_bus.events import EventType


class AlertStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"


class TrainUpdateEvent(BaseModel):
    """
    Contract 1: TRAIN_UPDATE telemetry event
    """
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    event_type: EventType = Field(default=EventType.TRAIN_UPDATE)
    train_id: str
    latitude: float = 0.0
    longitude: float = 0.0
    current_position_km: float = 0.0
    speed: float = 60.0
    current_speed_kmh: float = 60.0
    section: str = "MAIN_LINE"
    delay: float = 0.0
    current_delay_min: float = 0.0
    eta: Optional[str] = None
    priority: str = "NORMAL"
    train_priority: str = "NORMAL"
    current_signal: str = "GREEN"
    current_headway_min: float = 10.0
    safe_required_headway_min: float = 3.0
    platform_availability: str = "AVAILABLE"
    junction_status: str = "CLEAR"
    route_status: str = "NORMAL"
    has_train_ahead: bool = False
    distance_to_ahead_train_km: float = 100.0
    ahead_train_speed_kmh: float = 0.0
    speed_history: Optional[List[float]] = None
    position_history: Optional[List[float]] = None
    delay_history: Optional[List[float]] = None
    weather_condition: str = "CLEAR"
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class PredictionEvent(BaseModel):
    """
    Contract 2: PREDICTION event generated by ML inference (Step 12)
    """
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    event_type: EventType = Field(default=EventType.PREDICTION)
    train_id: str
    section: str = "MAIN_LINE"
    current_position_km: float = 0.0
    predicted_eta: str
    expected_delay_min: float = 0.0
    predicted_delay: float = 0.0  # Backward compatibility alias
    conflict_probability: float = 0.0
    potential_conflict: bool = False
    prediction_confidence: float = 0.85
    recommended_action: str = "PROCEED"
    recommendation: str = "PROCEED"
    estimated_time_saved_min: float = 0.0
    reasoning: Dict[str, Any] = Field(default_factory=dict)
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class VisionEvent(BaseModel):
    """
    Contract 3: VISION event generated by object/defect detection
    """
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    event_type: EventType = Field(default=EventType.VISION_DETECTION)
    object_type: str
    confidence: float
    location: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    bounding_box: Optional[List[float]] = None
    video_source: Optional[str] = None


class RiskAlert(BaseModel):
    """
    Contract 4: RISK ALERT generated by Risk Engine
    """
    alert_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    risk_score: float
    alert_level: str
    location: str
    related_train_ids: List[str] = Field(default_factory=list)
    related_events: List[str] = Field(default_factory=list)
    recommendation: str
    status: AlertStatus = AlertStatus.ACTIVE
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    escalated: bool = False
