"""
TrainSense FastAPI API Router
Defines REST API endpoints for /health, /trains, /alerts, /dashboard, and /alerts/{id}/acknowledge.
"""

from typing import Any, Dict, List
from fastapi import APIRouter, HTTPException, Path, status

from app.services.state_store import state_store

router = APIRouter()


@router.get("/health", summary="Health Check")
async def get_health() -> Dict[str, Any]:
    """Returns backend application and system health status."""
    return {
        "status": "healthy",
        "service": "TrainSense Backend API",
        "version": "0.1.0",
        "event_bus": "active",
        "ml_model": "loaded"
    }


@router.get("/trains", summary="Get Active Trains Telemetry & ML Predictions")
async def get_trains() -> List[Dict[str, Any]]:
    """Returns real-time telemetry and ML predictions for all active trains."""
    return state_store.get_trains()


@router.get("/alerts", summary="Get Operational Risk Alerts")
async def get_alerts() -> List[Dict[str, Any]]:
    """Returns all operational risk alerts generated by the Correlation Engine."""
    return state_store.get_alerts()


@router.get("/dashboard", summary="Get Consolidated Operational Dashboard State")
async def get_dashboard() -> Dict[str, Any]:
    """Returns consolidated system status, active trains, active alerts, and latest AI detections."""
    return state_store.get_dashboard_summary()


@router.post("/alerts/{alert_id}/acknowledge", summary="Acknowledge an Operational Alert")
async def acknowledge_alert(
    alert_id: str = Path(..., description="Unique ID of the alert to acknowledge")
) -> Dict[str, Any]:
    """Acknowledges an active operational alert by ID."""
    updated_alert = state_store.acknowledge_alert(alert_id)
    if not updated_alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert with ID '{alert_id}' not found."
        )
    return {
        "message": f"Alert '{alert_id}' successfully acknowledged.",
        "alert": updated_alert
    }
