"""
TrainSense FastAPI API Router (Steps 15 & 16)
Defines REST API endpoints (/health, /trains, /predictions, /predictions/{train_id}, /alerts, /dashboard, /alerts/{id}/acknowledge, /simulation/*, /demo/*)
and WebSocket real-time telemetry endpoint (/ws).
"""

from datetime import datetime, timezone
from typing import Any, Dict, List
from fastapi import APIRouter, HTTPException, Path, Query, status, WebSocket, WebSocketDisconnect

from app.services.demo_orchestrator import demo_orchestrator
from app.services.simulator import simulator
from app.services.state_store import state_store
from app.services.websocket_manager import ws_manager

router = APIRouter()


@router.get("/health", summary="Health Check")
async def get_health() -> Dict[str, Any]:
    """Returns backend application and system health status."""
    return {
        "status": "healthy",
        "service": "TrainSense Backend API",
        "version": "0.2.0",
        "event_bus": "active",
        "ml_model": "loaded",
        "websocket": "active",
        "simulator": simulator.scenario_name
    }


@router.get("/trains", summary="Get Active Trains Telemetry & ML Predictions")
async def get_trains() -> List[Dict[str, Any]]:
    """Returns real-time telemetry and ML predictions for all active trains."""
    return state_store.get_trains()


@router.get("/predictions", summary="Get All Active ML Predictions")
async def get_predictions() -> List[Dict[str, Any]]:
    """Returns real-time ML operational predictions (ETA, delay, conflict probability, action) for active trains."""
    return state_store.get_predictions()


@router.get("/predictions/{train_id}", summary="Get ML Prediction for Specific Train")
async def get_train_prediction(
    train_id: str = Path(..., description="Train ID identifier (e.g. LOCAL-101)")
) -> Dict[str, Any]:
    """Returns ML operational prediction for a specific train."""
    pred = state_store.get_prediction(train_id)
    if not pred:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No active ML prediction found for train '{train_id}'."
        )
    return pred


@router.get("/alerts", summary="Get Operational Risk Alerts")
async def get_alerts() -> List[Dict[str, Any]]:
    """Returns all operational risk alerts generated by the Correlation Engine."""
    return state_store.get_alerts()


@router.get("/dashboard", summary="Get Consolidated Operational Dashboard State")
async def get_dashboard() -> Dict[str, Any]:
    """Returns consolidated system status, active trains, active alerts, and latest AI detections."""
    return state_store.get_dashboard_summary()


@router.post("/alerts/{alert_id}/acknowledge", summary="Acknowledge an Operational Alert")
async def acknowledge_alert(
    alert_id: str = Path(..., description="Unique ID of the alert to acknowledge")
) -> Dict[str, Any]:
    """Acknowledges an active operational alert by ID."""
    updated_alert = state_store.acknowledge_alert(alert_id)
    if not updated_alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert with ID '{alert_id}' not found."
        )
    return {
        "message": f"Alert '{alert_id}' successfully acknowledged.",
        "alert": updated_alert
    }


# ----------------------------------------------------
# SIMULATION & DEMO SCENARIO CONTROL ENDPOINTS (Steps 56–58)
# ----------------------------------------------------

@router.get("/simulation/status", summary="Get Simulator Status")
async def get_simulation_status() -> Dict[str, Any]:
    """Returns current telemetry simulator running status and active scenario."""
    return simulator.get_status()


@router.post("/simulation/start", summary="Start Real-Time Telemetry Simulation")
async def start_simulation(
    interval_seconds: float = Query(2.0, ge=0.5, le=10.0, description="Telemetry broadcast interval in seconds")
) -> Dict[str, Any]:
    """Starts the real-time background telemetry simulator."""
    await simulator.start(interval_seconds=interval_seconds)
    return {
        "message": "Telemetry simulation started successfully.",
        "status": simulator.get_status()
    }


@router.post("/simulation/stop", summary="Stop Telemetry Simulation")
async def stop_simulation() -> Dict[str, Any]:
    """Stops the real-time background telemetry simulator."""
    await simulator.stop()
    return {
        "message": "Telemetry simulation stopped successfully.",
        "status": simulator.get_status()
    }


@router.post("/simulation/trigger-normal", summary="Trigger Scenario A: Normal Operation Scenario")
async def trigger_normal_scenario() -> Dict[str, Any]:
    """Triggers Scenario A: Normal clear-track railway operational telemetry."""
    result = await simulator.trigger_normal_scenario()
    return {
        "message": "Scenario A: Normal operations scenario triggered successfully.",
        "result": result
    }


@router.post("/simulation/trigger-conflict", summary="Trigger Scenario B/C: High-Risk Conflict Scenario")
async def trigger_conflict_scenario() -> Dict[str, Any]:
    """Triggers Scenario B/C: High-risk multi-modal conflict & vision intrusion scenario."""
    result = await simulator.trigger_high_risk_conflict_scenario()
    return {
        "message": "High-risk conflict scenario triggered successfully.",
        "result": result
    }


# ----------------------------------------------------
# END-TO-END DEMO & SYSTEM VERIFICATION ENDPOINTS (Steps 59–60)
# ----------------------------------------------------

@router.get("/demo/status", summary="Get End-to-End Subsystem Readiness Matrix")
async def get_demo_system_status() -> Dict[str, Any]:
    """Returns the readiness and health matrix across all 8 backend subsystems."""
    return demo_orchestrator.get_system_readiness()


@router.post("/demo/run-scenario", summary="Execute Full End-to-End Multi-Modal Demo Trace")
async def run_demo_scenario() -> Dict[str, Any]:
    """Executes full multi-modal scenario and returns complete end-to-end trace log."""
    return await demo_orchestrator.run_full_end_to_end_demo()


@router.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """
    WebSocket endpoint broadcasting real-time Event Bus events
    (PREDICTION, VISION_DETECTION, ALERT, TRAIN_UPDATE) to connected clients.
    """
    await ws_manager.connect(websocket)
    try:
        # Send initial connection status frame
        await websocket.send_json({
            "event_type": "SYSTEM_CONNECT",
            "message": "Connected to TrainSense Real-Time Telemetry & Alert Stream",
            "timestamp": datetime.now(timezone.utc).isoformat()
        })
        while True:
            # Maintain active connection and listen for client messages/pings
            data = await websocket.receive_text()
            await websocket.send_json({
                "event_type": "CLIENT_ACK",
                "received": data,
                "timestamp": datetime.now(timezone.utc).isoformat()
            })
    except WebSocketDisconnect:
        ws_manager.disconnect(websocket)
    except Exception:
        ws_manager.disconnect(websocket)
