"""
TrainSense FastAPI API Router
Defines REST API endpoints (/health, /trains, /alerts, /dashboard, /alerts/{id}/acknowledge)
and WebSocket real-time telemetry endpoint (/ws).
"""

from datetime import datetime, timezone
from typing import Any, Dict, List
from fastapi import APIRouter, HTTPException, Path, status, WebSocket, WebSocketDisconnect

from app.services.state_store import state_store
from app.services.websocket_manager import ws_manager

router = APIRouter()


@router.get("/health", summary="Health Check")
async def get_health() -> Dict[str, Any]:
    """Returns backend application and system health status."""
    return {
        "status": "healthy",
        "service": "TrainSense Backend API",
        "version": "0.1.0",
        "event_bus": "active",
        "ml_model": "loaded",
        "websocket": "active"
    }


@router.get("/trains", summary="Get Active Trains Telemetry & ML Predictions")
async def get_trains() -> List[Dict[str, Any]]:
    """Returns real-time telemetry and ML predictions for all active trains."""
    return state_store.get_trains()


@router.get("/alerts", summary="Get Operational Risk Alerts")
async def get_alerts() -> List[Dict[str, Any]]:
    """Returns all operational risk alerts generated by the Correlation Engine."""
    return state_store.get_alerts()


@router.get("/dashboard", summary="Get Consolidated Operational Dashboard State")
async def get_dashboard() -> Dict[str, Any]:
    """Returns consolidated system status, active trains, active alerts, and latest AI detections."""
    return state_store.get_dashboard_summary()


@router.post("/alerts/{alert_id}/acknowledge", summary="Acknowledge an Operational Alert")
async def acknowledge_alert(
    alert_id: str = Path(..., description="Unique ID of the alert to acknowledge")
) -> Dict[str, Any]:
    """Acknowledges an active operational alert by ID."""
    updated_alert = state_store.acknowledge_alert(alert_id)
    if not updated_alert:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Alert with ID '{alert_id}' not found."
        )
    return {
        "message": f"Alert '{alert_id}' successfully acknowledged.",
        "alert": updated_alert
    }


@router.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """
    WebSocket endpoint broadcasting real-time Event Bus events
    (PREDICTION, VISION_DETECTION, ALERT, TRAIN_UPDATE) to connected clients.
    """
    await ws_manager.connect(websocket)
    try:
        # Send initial connection status frame
        await websocket.send_json({
            "event_type": "SYSTEM_CONNECT",
            "message": "Connected to TrainSense Real-Time Telemetry & Alert Stream",
            "timestamp": datetime.now(timezone.utc).isoformat()
        })
        while True:
            # Maintain active connection and listen for client messages/pings
            data = await websocket.receive_text()
            await websocket.send_json({
                "event_type": "CLIENT_ACK",
                "received": data,
                "timestamp": datetime.now(timezone.utc).isoformat()
            })
    except WebSocketDisconnect:
        ws_manager.disconnect(websocket)
    except Exception:
        ws_manager.disconnect(websocket)
